# Generated by Django 5.1.3 on 2025-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_city_options_alter_city_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payment_status',
            field=models.CharField(choices=[('Not Enroll', 'Not Enroll'), ('Enroll Pending', 'Enroll Pending'), ('Enrolled', 'Enrolled')], default='Not Enroll', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
