# Generated by Django 5.1.3 on 2025-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_account_payment_status_account_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unique',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
