# Generated by Django 5.1.3 on 2025-03-28 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_corporatediscount_discount_mentorshipdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('candidate_status', models.CharField(choices=[('Applied', 'Applied'), ('Select', 'Select'), ('Pending', 'Pending'), ('Reject', 'Reject'), ('EXPIRE', 'EXPIRE'), ('DirectSelect', 'DirectSelect')], default='Applied', max_length=12)),
                ('applied', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('program_status', models.CharField(choices=[('Running', 'Running'), ('Hold', 'Hold'), ('Completed', 'Completed'), ('Applied', 'Applied')], default='Applied', max_length=12)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corporate Training',
                'verbose_name_plural': 'Corporate Trainings',
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('candidate_status', models.CharField(choices=[('Applied', 'Applied'), ('Select', 'Select'), ('Pending', 'Pending'), ('Reject', 'Reject'), ('EXPIRE', 'EXPIRE'), ('DirectSelect', 'DirectSelect')], default='Applied', max_length=12)),
                ('applied', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('program_status', models.CharField(choices=[('Running', 'Running'), ('Hold', 'Hold'), ('Completed', 'Completed'), ('Applied', 'Applied')], default='Applied', max_length=12)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship',
                'verbose_name_plural': 'Mentorships',
            },
        ),
    ]
