# Generated by Django 5.1.3 on 2025-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_corporatetraining_mentorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatetraining',
            name='course_name',
            field=models.CharField(default='Unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='course_name',
            field=models.CharField(default='Unknown', max_length=12),
        ),
    ]
