# Generated by Django 5.1.3 on 2025-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_corporatetraining_course_name_mentorship_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatetraining',
            name='current_year',
            field=models.CharField(default='Unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='corporatetraining',
            name='passing_year',
            field=models.CharField(default='Unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='corporatetraining',
            name='year_of_Admission',
            field=models.CharField(default='Unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='current_year',
            field=models.CharField(default='Unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='passing_year',
            field=models.CharField(default='Unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='year_of_Admission',
            field=models.CharField(default='Unknown', max_length=12),
        ),
    ]
