# Generated by Django 5.1.3 on 2025-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_corporatetraining_current_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatetraining',
            name='current_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corporatetraining',
            name='passing_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corporatetraining',
            name='year_of_Admission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='current_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='passing_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='year_of_Admission',
            field=models.IntegerField(default=0),
        ),
    ]
