# Generated by Django 5.1.3 on 2025-03-29 07:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_corporatetraining_current_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_program', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('original_price', models.PositiveIntegerField()),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount as a percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('training_description', models.TextField()),
                ('skills_you_will_gain', models.TextField()),
                ('What_you_Will_learm', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Not Enroll', 'Not Enroll'), ('Enroll Pending', 'Enroll Pending'), ('Enrolled', 'Enrolled')], default='Not Enroll', max_length=15)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('applied', models.CharField(choices=[('Running', 'Running'), ('Hold', 'Hold'), ('Completed', 'Completed'), ('Applied', 'Applied')], default='Not Applied', max_length=20)),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('TrainingProgram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_details', to='accounts.trainingprogram')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
