# Generated by Django 5.1.3 on 2025-03-29 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_trainingprogram_trainingprogramapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveProjectProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LiveProject_program', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('original_price', models.PositiveIntegerField()),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount as a percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('LiveProject_description', models.TextField()),
                ('skills_you_will_gain', models.TextField()),
                ('What_you_Will_learm', models.TextField(default='')),
            ],
        ),
    ]
