# Generated by Django 5.1.3 on 2025-03-29 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_liveprojecthub_delete_liveprojectprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveProjectHubApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Not Enroll', 'Not Enroll'), ('Enroll Pending', 'Enroll Pending'), ('Enrolled', 'Enrolled')], default='Not Enroll', max_length=15)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('applied', models.CharField(choices=[('Running', 'Running'), ('Hold', 'Hold'), ('Completed', 'Completed'), ('Applied', 'Applied')], default='Not Applied', max_length=20)),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('LiveProjectHub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LiveProject_details', to='accounts.liveprojecthub')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LiveProject_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
