# Generated by Django 5.1.3 on 2025-03-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_liveprojecthubapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveprojecthubapplication',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='trainingprogramapplication',
            name='time_end',
        ),
    ]
