# Generated by Django 5.1.3 on 2025-03-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_liveprojecthubapplication_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveprojecthubapplication',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogramapplication',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
