# Generated by Django 5.1.3 on 2025-03-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0005_alter_experience_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='current_Company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='employemt_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
