# Generated by Django 5.1.3 on 2025-03-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0006_remove_experience_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='current_Company',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='employemt_type',
        ),
    ]
