# Generated by Django 5.1.3 on 2025-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0007_remove_experience_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='current_Company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='employemt_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
