# Generated by Django 5.1.3 on 2025-03-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0008_experience_current_company_experience_employemt_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
