# Generated by Django 5.1.3 on 2025-03-20 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0010_remove_experience_user_project_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='current_Company',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='employemt_type',
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
