# Generated by Django 5.1.3 on 2025-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0012_alter_experience_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='employement_type',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
