# Generated by Django 5.1.3 on 2025-03-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0013_experience_employement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='current_company',
            field=models.BooleanField(default=False),
        ),
    ]
