# Generated by Django 5.1.3 on 2025-03-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0014_experience_current_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='employement_type',
        ),
    ]
