# Generated by Django 5.1.3 on 2025-03-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0015_remove_experience_employement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='current_company',
        ),
    ]
